/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import controler.Service;
import dao.PolicialDao;
import model.Curso;
import model.Telefone;

/**
 *
 * @author Cephas
 */
public class JIFCadastrarTelefone extends javax.swing.JInternalFrame {

	private int linhaSelecionada = -1;
	private static tmListaPoliciais modelo;
	public PolicialDao pdao = new PolicialDao();
	
    /**
     * Creates new form JIFCadastrarAlteracao
     */
    public JIFCadastrarTelefone() {
    	setResizable(true);
        initComponents();
        refreshPopulate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbDadosPms = new javax.swing.JTable();
        
        modelo = new tmListaPoliciais(/*pdao.listar()*/);
        tbDadosPms.setModel(modelo);
        
        
        tbDadosPms.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		linhaSelecionada = tbDadosPms.getSelectedRow();
        	}
        });

        setClosable(true);

        btnConfirmar.setText("Confirmar cadastro");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero:");

        jLabel2.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Clique na linha do policial que receber\u00E1 cadastramento de telefone");

       
        jScrollPane4.setViewportView(tbDadosPms);
        if (tbDadosPms.getColumnModel().getColumnCount() > 0) {
        	tbDadosPms.getColumnModel().getColumn(0).setMinWidth(0);
        	tbDadosPms.getColumnModel().getColumn(0).setPreferredWidth(0);
        	tbDadosPms.getColumnModel().getColumn(0).setMaxWidth(0);
        }
        tbDadosPms.setVisible(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jScrollPane4, GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        					.addContainerGap())
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel4)
        					.addGap(233))))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(jLabel4)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane4, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);
        tpTipo = new javax.swing.JTextPane();
        tpNumero = new javax.swing.JTextPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(296)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(tpTipo, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(tpNumero, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(525, Short.MAX_VALUE)
        			.addComponent(btnConfirmar)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(tpTipo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2)
        				.addComponent(jLabel1)
        				.addComponent(tpNumero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(btnConfirmar)
        			.addGap(220))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    	Telefone tel = new Telefone();
    	tel.setTipo(tpTipo.getText());
    	tel.setNumero(tpNumero.getText());
		if(linhaSelecionada != -1){
			Service sv = new Service();
			sv.cadastrarTelefone(tel, modelo.getPolicial(linhaSelecionada));
		}
    	
    }        
    
    public void refreshPopulate(){
    	modelo.getLinhas().clear();
    	modelo.setLinhas(pdao.listar());
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbDadosPms;
    private javax.swing.JTextPane tpTipo;
    private javax.swing.JTextPane tpNumero;
}
