/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import controler.Service;
import model.Policial;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Cephas
 */
public class JIFCadastrarPolicial extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFDetalhesPolicial
     */
    public JIFCadastrarPolicial() {
    	setResizable(true);
    	setClosable(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TpNome = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TpNomePai = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TpNomeMae = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TpEstadoCivil = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        TpNaturalidade = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TpTipoSangue = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TpDataNascimento = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TpGraduacao = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        TpNomeGuerra = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        TpDataInclusao = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        TpDataExclusao = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        TpProcedencia = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        TpEspecialidade = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        TpMatricula = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        TpNumero = new javax.swing.JTextPane();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        TpRgPm = new javax.swing.JTextPane();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        TpCpf = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        TpRgCivil = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        TpReservista = new javax.swing.JTextPane();
        TpReservista.setText(" ");
        jLabel21 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        TpPisPasep = new javax.swing.JTextPane();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        TpCorPele = new javax.swing.JTextPane();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        TpCorOlhos = new javax.swing.JTextPane();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane27 = new javax.swing.JScrollPane();
        TpCorCbelos = new javax.swing.JTextPane();
        jScrollPane28 = new javax.swing.JScrollPane();
        TpAltura = new javax.swing.JTextPane();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        TpGrauInstrucao = new javax.swing.JTextPane();
        jScrollPane29 = new javax.swing.JScrollPane();
        TpEmail = new javax.swing.JTextPane();
        jLabel27 = new javax.swing.JLabel();
        btnConfirmarcadastro = new javax.swing.JButton();
        btnConfirmarcadastro.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	
        		Policial pm = new Policial();
        		
				pm.setAltura(Float.valueOf(TpAltura.getText()));
				pm.setCorCabelos(TpCorCbelos.getText());
				pm.setCorOlhos(TpCorOlhos.getText());
				pm.setCor(TpCorPele.getText());
				pm.setCpf(TpCpf.getText());
				pm.setDataNascimento(TpDataNascimento.getText());		
				pm.setDataExclusao(TpDataExclusao.getText());
				pm.setDataInclusao(TpDataInclusao.getText());
				pm.setEmail(TpEmail.getText());
				pm.setEspecialidade(TpEspecialidade.getText());
				pm.setGraduacao(TpGraduacao.getText());
				pm.setGrauInstrucao(TpGrauInstrucao.getText());
				pm.setMatricula(TpMatricula.getText());
				pm.setNaturalidade(TpNaturalidade.getText());
				pm.setNome(TpNome.getText());
				pm.setNomeGuerra(TpNomeGuerra.getText());
				pm.setNomeMae(TpNomeMae.getText());
				pm.setNomePai(TpNomePai.getText());
				pm.setNumero(Integer.valueOf(TpNumero.getText()));
				pm.setPisPasep(TpPisPasep.getText());
				pm.setProcedencia(TpProcedencia.getText());
				pm.setReservista(TpReservista.getText());
				pm.setRgCivil(TpRgCivil.getText());
				pm.setRgPm(TpRgPm.getText());
				pm.setTipoSangue(TpTipoSangue.getText());
				pm.setEstadoCivil(TpEstadoCivil.getText());

				Service sv = new Service();
				sv.cadastrarPolicial(pm);
        	}
        });

        jLabel1.setText("Nome:");
        TpNome.setToolTipText("");
        jScrollPane1.setViewportView(TpNome);

        jLabel2.setText("Nome de guerra:");

        jLabel3.setText("Nome do pai:");
        jScrollPane3.setViewportView(TpNomePai);

        jLabel4.setText("Nome da mãe:");
        jScrollPane4.setViewportView(TpNomeMae);

        jLabel5.setText("Estado civil:");
        jScrollPane5.setViewportView(TpEstadoCivil);
        jScrollPane6.setViewportView(TpNaturalidade);

        jLabel6.setText("Naturalidade:");

        jLabel7.setText("Tipo de sangue:");
        jScrollPane7.setViewportView(TpTipoSangue);

        jLabel8.setText("Data de nascimento:");

        jLabel9.setText("Data de inclusão:");

        jLabel10.setText("Data de exclusão:");

        jLabel11.setText("Procedência:");
        jScrollPane9.setViewportView(TpDataNascimento);

        jLabel12.setText("Graduação:");
        jScrollPane10.setViewportView(TpGraduacao);
        jScrollPane11.setViewportView(TpNomeGuerra);
        jScrollPane13.setViewportView(TpDataInclusao);
        jScrollPane14.setViewportView(TpDataExclusao);
        jScrollPane15.setViewportView(TpProcedencia);
        jScrollPane16.setViewportView(TpEspecialidade);

        jLabel14.setText("Especialidade:");

        jLabel15.setText("Matrícula:");
        jScrollPane17.setViewportView(TpMatricula);

        jLabel16.setText("Número:");
        jScrollPane18.setViewportView(TpNumero);

        jLabel17.setText("Rg PM:");
        jScrollPane19.setViewportView(TpRgPm);

        jLabel18.setText("CPF:");
        jScrollPane20.setViewportView(TpCpf);
        jScrollPane21.setViewportView(TpRgCivil);

        jLabel19.setText("RG Civil:");

        jLabel20.setText("Reservista:");
        jScrollPane22.setViewportView(TpReservista);

        jLabel21.setText("Pis/Pasep:");
        jScrollPane23.setViewportView(TpPisPasep);

        jLabel22.setText("Altura:");

        jLabel23.setText("Cor da pele:");
        jScrollPane25.setViewportView(TpCorPele);

        jLabel24.setText("Cor dos olhos:");
        jScrollPane26.setViewportView(TpCorOlhos);

        jLabel25.setText("Cor dos cabelos:");
        jScrollPane27.setViewportView(TpCorCbelos);
        jScrollPane28.setViewportView(TpAltura);

        jLabel26.setText("Grau de instrução:");

        TpGrauInstrucao.setEditable(false);
        jScrollPane24.setViewportView(TpGrauInstrucao);
        jScrollPane29.setViewportView(TpEmail);

        jLabel27.setText("Email:");

        btnConfirmarcadastro.setText("Confirmar cadastro");
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(75)
        			.addComponent(jLabel1)
        			.addGap(7)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 438, GroupLayout.PREFERRED_SIZE)
        			.addGap(24)
        			.addComponent(jLabel5)
        			.addGap(4)
        			.addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(37)
        			.addComponent(jLabel4)
        			.addGap(7)
        			.addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 438, GroupLayout.PREFERRED_SIZE)
        			.addGap(4)
        			.addComponent(jLabel7)
        			.addGap(4)
        			.addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(46)
        			.addComponent(jLabel3)
        			.addGap(4)
        			.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 438, GroupLayout.PREFERRED_SIZE)
        			.addGap(16)
        			.addComponent(jLabel6)
        			.addGap(4)
        			.addComponent(jScrollPane6, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(10)
        			.addComponent(jLabel8)
        			.addGap(4)
        			.addComponent(jScrollPane9, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
        			.addGap(28)
        			.addComponent(jLabel26)
        			.addGap(4)
        			.addComponent(jScrollPane24, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE))
        		.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 819, GroupLayout.PREFERRED_SIZE)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(52)
        			.addComponent(jLabel12)
        			.addGap(4)
        			.addComponent(jScrollPane10, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        			.addGap(16)
        			.addComponent(jLabel14)
        			.addGap(1)
        			.addComponent(jScrollPane16, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        			.addGap(35)
        			.addComponent(jLabel11)
        			.addGap(4)
        			.addComponent(jScrollPane15, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(27)
        			.addComponent(jLabel2)
        			.addGap(4)
        			.addComponent(jScrollPane11, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        			.addGap(34)
        			.addComponent(jLabel15)
        			.addGap(4)
        			.addComponent(jScrollPane17, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        			.addGap(14)
        			.addComponent(jLabel9)
        			.addGap(4)
        			.addComponent(jScrollPane13, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(74)
        			.addComponent(jLabel17)
        			.addGap(4)
        			.addComponent(jScrollPane19, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        			.addGap(40)
        			.addComponent(jLabel16)
        			.addGap(4)
        			.addComponent(jScrollPane18, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        			.addGap(10)
        			.addComponent(jLabel10)
        			.addGap(4)
        			.addComponent(jScrollPane14, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE))
        		.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 819, GroupLayout.PREFERRED_SIZE)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(70)
        			.addComponent(jLabel19)
        			.addGap(4)
        			.addComponent(jScrollPane21, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        			.addGap(57)
        			.addComponent(jLabel18)
        			.addGap(4)
        			.addComponent(jScrollPane20, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(55)
        			.addComponent(jLabel20)
        			.addGap(4)
        			.addComponent(jScrollPane22, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        			.addGap(30)
        			.addComponent(jLabel21)
        			.addGap(4)
        			.addComponent(jScrollPane23, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(78)
        			.addComponent(jLabel22)
        			.addGap(4)
        			.addComponent(jScrollPane28, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        			.addGap(194)
        			.addComponent(jLabel27)
        			.addGap(4)
        			.addComponent(jScrollPane29, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(52)
        			.addComponent(jLabel23)
        			.addGap(4)
        			.addComponent(jScrollPane25, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE))
        		.addComponent(jSeparator3, GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(42)
        					.addComponent(jLabel24)
        					.addGap(4)
        					.addComponent(jScrollPane26, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(32)
        					.addComponent(jLabel25)
        					.addGap(4)
        					.addComponent(jScrollPane27, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
        			.addComponent(btnConfirmarcadastro, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE)
        			.addGap(97))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(11)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(9)
        					.addComponent(jLabel1))
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel5))
        				.addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(5)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(9)
        					.addComponent(jLabel4))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(1)
        					.addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel7))
        				.addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(5)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(9)
        					.addComponent(jLabel3))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(1)
        					.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel6))
        				.addComponent(jScrollPane6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(6)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel8))
        				.addComponent(jScrollPane9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel26))
        				.addComponent(jScrollPane24, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(6)
        			.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        			.addGap(6)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel12))
        				.addComponent(jScrollPane10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel14))
        				.addComponent(jScrollPane16, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel11))
        				.addComponent(jScrollPane15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(6)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel2))
        				.addComponent(jScrollPane11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel15))
        				.addComponent(jScrollPane17, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel9))
        				.addComponent(jScrollPane13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(6)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel17))
        				.addComponent(jScrollPane19, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel16))
        				.addComponent(jScrollPane18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel10))
        				.addComponent(jScrollPane14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(11)
        			.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        			.addGap(6)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(9)
        					.addComponent(jLabel19))
        				.addComponent(jScrollPane21, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel18))
        				.addComponent(jScrollPane20, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(11)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel20))
        				.addComponent(jScrollPane22, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel21))
        				.addComponent(jScrollPane23, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(11)
        			.addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel22))
        				.addComponent(jScrollPane28, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel27))
        				.addComponent(jScrollPane29, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(6)
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(8)
        							.addComponent(jLabel23))
        						.addComponent(jScrollPane25, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(6)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(8)
        							.addComponent(jLabel24))
        						.addComponent(jScrollPane26, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(6)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(8)
        							.addComponent(jLabel25))
        						.addComponent(jScrollPane27, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addComponent(btnConfirmarcadastro)))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JTextPane TpEstadoCivil;
    private javax.swing.JTextPane TpAltura;
    private javax.swing.JTextPane TpCorCbelos;
    private javax.swing.JTextPane TpCorOlhos;
    private javax.swing.JTextPane TpCorPele;
    private javax.swing.JTextPane TpCpf;
    private javax.swing.JTextPane TpDataExclusao;
    private javax.swing.JTextPane TpDataInclusao;
    private javax.swing.JTextPane TpDataNascimento;
    private javax.swing.JTextPane TpEmail;
    private javax.swing.JTextPane TpEspecialidade;
    private javax.swing.JTextPane TpGraduacao;
    private javax.swing.JTextPane TpGrauInstrucao;
    private javax.swing.JTextPane TpMatricula;
    private javax.swing.JTextPane TpNaturalidade;
    private javax.swing.JTextPane TpNome;
    private javax.swing.JTextPane TpNomeGuerra;
    private javax.swing.JTextPane TpNomeMae;
    private javax.swing.JTextPane TpNomePai;
    private javax.swing.JTextPane TpNumero;
    private javax.swing.JTextPane TpPisPasep;
    private javax.swing.JTextPane TpProcedencia;
    private javax.swing.JTextPane TpReservista;
    private javax.swing.JTextPane TpRgCivil;
    private javax.swing.JTextPane TpRgPm;
    private javax.swing.JTextPane TpTipoSangue;
    private javax.swing.JButton btnConfirmarcadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration                   
}


