/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;

import controler.Service;
import model.Policial;

/**
 *
 * @author Cephas
 */
public class JIFDetalhesPolicial extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFDetalhesPolicial
     */
	
	private Policial policial = new Policial();
	
    public JIFDetalhesPolicial(Policial policial) {
    	setClosable(true);
        this.policial = policial;
    	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnConfirmar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		        		
				policial.setAltura(Float.valueOf(TpAltura.getText()));
				policial.setCorCabelos(TpCorCbelos.getText());
				policial.setCorOlhos(TpCorOlhos.getText());
				policial.setCor(TpCorPele.getText());
				policial.setCpf(TpCpf.getText());
				policial.setDataNascimento(TpDataNascimento.getText());		
				policial.setDataExclusao(TpDataExclusao.getText());
				policial.setDataInclusao(TpDataInclusao.getText());
				policial.setEmail(TpEmail.getText());
				policial.setEspecialidade(TpEspecialidade.getText());
				policial.setGraduacao(TpGraduacao.getText());
				policial.setGrauInstrucao(TpGrauInstrucao.getText());
				policial.setMatricula(TpMatricula.getText());
				policial.setNaturalidade(TpNaturalidade.getText());
				policial.setNome(TpNome.getText());
				policial.setNomeGuerra(TpNomeGuerra.getText());
				policial.setNomeMae(TpNomeMae.getText());
				policial.setNomePai(TpNomePai.getText());
				policial.setNumero(Integer.valueOf(TpNumero.getText()));
				policial.setPisPasep(TpPisPasep.getText());
				policial.setProcedencia(TpProcedencia.getText());
				policial.setReservista(TpReservista.getText());
				policial.setRgCivil(TpRgCivil.getText());
				policial.setRgPm(TpRgPm.getText());
				policial.setTipoSangue(TpTipoSangue.getText());
				policial.setEstadoCivil(TpEstadoCivil.getText());
				
				Service service = new Service();
				service.atualizarPolicial(policial);
        		
        		
        	}
        });
        btnConfirmar.setEnabled(false);
        
        
        btnEditar = new javax.swing.JButton();
        btnEditar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		TpAltura.setEditable(true);
        		TpCorCbelos.setEditable(true);
        		TpCorOlhos.setEditable(true);
        		TpCorPele.setEditable(true);
        		TpCpf.setEditable(true);
        		TpDataNascimento.setEditable(true);
        		TpDataExclusao.setEditable(true);
        		TpDataInclusao.setEditable(true);
        		TpEmail.setEditable(true);
        		TpEspecialidade.setEditable(true);
        		TpGraduacao.setEditable(true);
        		TpGrauInstrucao.setEditable(true);
        		TpMatricula.setEditable(true);
        		TpNaturalidade.setEditable(true);
        		TpNome.setEditable(true);
        		TpNomeGuerra.setEditable(true);
        		TpNomeMae.setEditable(true);
        		TpNomePai.setEditable(true);
        		TpNumero.setEditable(true);
        		TpPisPasep.setEditable(true);
        		TpProcedencia.setEditable(true);
        		TpReservista.setEditable(true);
        		TpRgCivil.setEditable(true);
        		TpRgPm.setEditable(true);
        		TpTipoSangue.setEditable(true);
        		TpEstadoCivil.setEditable(true);

        		btnConfirmar.setEnabled(true);
        	}
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Nome de guerra:");

        jLabel3.setText("Nome do pai:");

        jLabel4.setText("Nome da mãe:");

        jLabel5.setText("Estado civil:");

        jLabel6.setText("Naturalidade:");

        jLabel7.setText("Tipo de sangue:");

        jLabel8.setText("Data de nascimento:");

        jLabel9.setText("Data de inclusão:");

        jLabel10.setText("Data de exclusão:");

        jLabel11.setText("Procedência:");

        jLabel12.setText("Graduação:");

        jLabel14.setText("Especialidade:");

        jLabel15.setText("Matrícula:");

        jLabel16.setText("Número:");

        jLabel17.setText("Rg PM:");

        jLabel18.setText("CPF:");

        jLabel19.setText("RG Civil:");

        jLabel20.setText("Reservista:");

        jLabel21.setText("Pis/Pasep:");

        jLabel22.setText("Altura:");

        jLabel23.setText("Cor da pele:");

        jLabel24.setText("Cor dos olhos:");

        jLabel25.setText("Cor dos cabelos:");

        jLabel26.setText("Grau de instrução:");

        jLabel27.setText("Email:");

        btnConfirmar.setText("Confirmar");

        btnEditar.setText("Editar");
        TpNome = new javax.swing.JTextPane();
        
                TpNome.setEditable(false);
                TpNome.setToolTipText("");
                TpNome.setText(policial.getNome());
        TpNomeMae = new javax.swing.JTextPane();
        
                TpNomeMae.setEditable(false);
                TpNomeMae.setText(policial.getNomeMae());
        TpNomePai = new javax.swing.JTextPane();
        
                TpNomePai.setEditable(false);
                TpNomePai.setText(policial.getNomePai());
        TpEstadoCivil = new javax.swing.JTextPane();
        
                TpEstadoCivil.setEditable(false);
                TpEstadoCivil.setText(policial.getEstadoCivil());
                TpTipoSangue = new javax.swing.JTextPane();
                
                        TpTipoSangue.setEditable(false);
                        TpTipoSangue.setText(policial.getTipoSangue());
                        TpNaturalidade = new javax.swing.JTextPane();
                        
                                TpNaturalidade.setEditable(false);
                                TpNaturalidade.setText(policial.getNaturalidade());
                                TpDataNascimento = new javax.swing.JTextPane();
                                
                                        TpDataNascimento.setEditable(false);
                                        TpDataNascimento.setText(policial.getDataNascimento());
                                        TpNomeGuerra = new javax.swing.JTextPane();
                                        
                                                TpNomeGuerra.setEditable(false);
                                                TpNomeGuerra.setText(policial.getNomeGuerra());
                                                TpGraduacao = new javax.swing.JTextPane();
                                                
                                                        TpGraduacao.setEditable(false);
                                                        TpGraduacao.setText(policial.getGraduacao());
                                                        TpRgPm = new javax.swing.JTextPane();
                                                        
                                                                TpRgPm.setEditable(false);
                                                                TpRgPm.setText(policial.getRgPm());
                                                                TpEspecialidade = new javax.swing.JTextPane();
                                                                
                                                                        TpEspecialidade.setEditable(false);
                                                                        TpEspecialidade.setText(policial.getEspecialidade());
                                                                        TpMatricula = new javax.swing.JTextPane();
                                                                        
                                                                                TpMatricula.setEditable(false);
                                                                                TpMatricula.setText(policial.getMatricula());
                                                                                TpNumero = new javax.swing.JTextPane();
                                                                                
                                                                                        TpNumero.setEditable(false);
                                                                                        TpNumero.setText(String.valueOf(policial.getNumero()));
                                                                                        TpGrauInstrucao = new javax.swing.JTextPane();
                                                                                        
                                                                                                TpGrauInstrucao.setEditable(false);
                                                                                                TpGrauInstrucao.setText(policial.getGrauInstrucao());
                                                                                                TpProcedencia = new javax.swing.JTextPane();
                                                                                                
                                                                                                        TpProcedencia.setEditable(false);
                                                                                                        TpProcedencia.setText(policial.getProcedencia());
                                                                                                        TpDataInclusao = new javax.swing.JTextPane();
                                                                                                        
                                                                                                                TpDataInclusao.setEditable(false);
                                                                                                                TpDataInclusao.setText(policial.getDataInclusao());
                                                                                                                TpDataExclusao = new javax.swing.JTextPane();
                                                                                                                
                                                                                                                        TpDataExclusao.setEditable(false);
                                                                                                                        TpDataExclusao.setText(policial.getDataExclusao());
                                                                                                                        TpEmail = new javax.swing.JTextPane();
                                                                                                                        
                                                                                                                                TpEmail.setEditable(false);
                                                                                                                                TpEmail.setText(policial.getEmail());
                                                                                                                                TpPisPasep = new javax.swing.JTextPane();
                                                                                                                                
                                                                                                                                        TpPisPasep.setEditable(false);
                                                                                                                                        TpPisPasep.setText(policial.getPisPasep());
                                                                                                                                        TpCpf = new javax.swing.JTextPane();
                                                                                                                                        
                                                                                                                                                TpCpf.setEditable(false);
                                                                                                                                                TpCpf.setText(policial.getCpf());
                                                                                                                                                TpRgCivil = new javax.swing.JTextPane();
                                                                                                                                                
                                                                                                                                                        TpRgCivil.setEditable(false);
                                                                                                                                                        TpRgCivil.setText(policial.getRgCivil());
                                                                                                                                                        TpReservista = new javax.swing.JTextPane();
                                                                                                                                                        
                                                                                                                                                                TpReservista.setEditable(false);
                                                                                                                                                                TpReservista.setText(policial.getReservista());
                                                                                                                                                                TpCorPele = new javax.swing.JTextPane();
                                                                                                                                                                
                                                                                                                                                                        TpCorPele.setEditable(false);
                                                                                                                                                                        TpCorPele.setText(policial.getCor());
                                                                                                                                                                        TpAltura = new javax.swing.JTextPane();
                                                                                                                                                                        
                                                                                                                                                                                TpAltura.setEditable(false);
                                                                                                                                                                                
                                                                                                                                                                                        TpAltura.setText(String.valueOf(policial.getAltura()));
                                                                                                                                                                                        TpCorOlhos = new javax.swing.JTextPane();
                                                                                                                                                                                        
                                                                                                                                                                                                TpCorOlhos.setEditable(false);
                                                                                                                                                                                                TpCorOlhos.setText(policial.getCorOlhos());
                                                                                                                                                                                                TpCorCbelos = new javax.swing.JTextPane();
                                                                                                                                                                                                
                                                                                                                                                                                                        TpCorCbelos.setEditable(false);
                                                                                                                                                                                                        TpCorCbelos.setText(policial.getCorCabelos());
                                                                                                                                                                                                        GroupLayout groupLayout = new GroupLayout(getContentPane());
                                                                                                                                                                                                        groupLayout.setHorizontalGroup(
                                                                                                                                                                                                        	groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(59)
                                                                                                                                                                                                        			.addComponent(jLabel1)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpNome, GroupLayout.PREFERRED_SIZE, 345, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(65)
                                                                                                                                                                                                        			.addComponent(jLabel5)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpEstadoCivil, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(21)
                                                                                                                                                                                                        			.addComponent(jLabel4)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpNomeMae, GroupLayout.PREFERRED_SIZE, 345, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(45)
                                                                                                                                                                                                        			.addComponent(jLabel7)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpTipoSangue, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(27)
                                                                                                                                                                                                        			.addComponent(jLabel3)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpNomePai, GroupLayout.PREFERRED_SIZE, 345, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(57)
                                                                                                                                                                                                        			.addComponent(jLabel6)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpNaturalidade, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(462)
                                                                                                                                                                                                        			.addComponent(jLabel8)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpDataNascimento, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(1116)
                                                                                                                                                                                                        			.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(34)
                                                                                                                                                                                                        			.addComponent(jLabel12)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpGraduacao, GroupLayout.PREFERRED_SIZE, 142, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(20)
                                                                                                                                                                                                        			.addComponent(jLabel14)
                                                                                                                                                                                                        			.addGap(3)
                                                                                                                                                                                                        			.addComponent(TpEspecialidade, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(40)
                                                                                                                                                                                                        			.addComponent(jLabel11)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpProcedencia, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(9)
                                                                                                                                                                                                        			.addComponent(jLabel2)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpNomeGuerra, GroupLayout.PREFERRED_SIZE, 142, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(41)
                                                                                                                                                                                                        			.addComponent(jLabel15)
                                                                                                                                                                                                        			.addGap(3)
                                                                                                                                                                                                        			.addComponent(TpMatricula, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(19)
                                                                                                                                                                                                        			.addComponent(jLabel9)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpDataInclusao, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(56)
                                                                                                                                                                                                        			.addComponent(jLabel17)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpRgPm, GroupLayout.PREFERRED_SIZE, 142, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(47)
                                                                                                                                                                                                        			.addComponent(jLabel16)
                                                                                                                                                                                                        			.addGap(3)
                                                                                                                                                                                                        			.addComponent(TpNumero, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(15)
                                                                                                                                                                                                        			.addComponent(jLabel10)
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addComponent(TpDataExclusao, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(1116)
                                                                                                                                                                                                        			.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(29)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(26)
                                                                                                                                                                                                        					.addComponent(jLabel22))
                                                                                                                                                                                                        				.addComponent(jLabel23))
                                                                                                                                                                                                        			.addGap(3)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addComponent(TpAltura, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        				.addComponent(TpCorPele, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        			.addGap(44)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(17)
                                                                                                                                                                                                        					.addComponent(jLabel19))
                                                                                                                                                                                                        				.addComponent(jLabel20, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        			.addGap(3)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addComponent(TpRgCivil, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        				.addComponent(TpReservista, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        			.addGap(52)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(27)
                                                                                                                                                                                                        					.addComponent(jLabel18))
                                                                                                                                                                                                        				.addComponent(jLabel21))
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addComponent(TpCpf, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        				.addComponent(TpPisPasep, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(19)
                                                                                                                                                                                                        			.addComponent(jLabel24)
                                                                                                                                                                                                        			.addGap(3)
                                                                                                                                                                                                        			.addComponent(TpCorOlhos, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(73)
                                                                                                                                                                                                        			.addComponent(jLabel27)
                                                                                                                                                                                                        			.addGap(3)
                                                                                                                                                                                                        			.addComponent(TpEmail, GroupLayout.PREFERRED_SIZE, 408, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(9)
                                                                                                                                                                                                        			.addComponent(jLabel25)
                                                                                                                                                                                                        			.addGap(2)
                                                                                                                                                                                                        			.addComponent(TpCorCbelos, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(12)
                                                                                                                                                                                                        			.addComponent(jLabel26)
                                                                                                                                                                                                        			.addGap(3)
                                                                                                                                                                                                        			.addComponent(TpGrauInstrucao, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(33)
                                                                                                                                                                                                        			.addComponent(btnEditar, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(10)
                                                                                                                                                                                                        			.addComponent(btnConfirmar, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(40)
                                                                                                                                                                                                        			.addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        );
                                                                                                                                                                                                        groupLayout.setVerticalGroup(
                                                                                                                                                                                                        	groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        		.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        			.addGap(12)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(7)
                                                                                                                                                                                                        					.addComponent(jLabel1))
                                                                                                                                                                                                        				.addComponent(TpNome, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(jLabel5))
                                                                                                                                                                                                        				.addComponent(TpEstadoCivil, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        			.addGap(7)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(7)
                                                                                                                                                                                                        					.addComponent(jLabel4))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(1)
                                                                                                                                                                                                        					.addComponent(TpNomeMae, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(jLabel7))
                                                                                                                                                                                                        				.addComponent(TpTipoSangue, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        			.addGap(7)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(7)
                                                                                                                                                                                                        					.addComponent(jLabel3))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(1)
                                                                                                                                                                                                        					.addComponent(TpNomePai, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(5)
                                                                                                                                                                                                        					.addComponent(jLabel6))
                                                                                                                                                                                                        				.addComponent(TpNaturalidade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        			.addGap(9)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(jLabel8))
                                                                                                                                                                                                        				.addComponent(TpDataNascimento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        			.addGap(9)
                                                                                                                                                                                                        			.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(8)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(7)
                                                                                                                                                                                                        					.addComponent(jLabel12))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(1)
                                                                                                                                                                                                        					.addComponent(TpGraduacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(3)
                                                                                                                                                                                                        					.addComponent(jLabel14))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(3)
                                                                                                                                                                                                        					.addComponent(TpEspecialidade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(3)
                                                                                                                                                                                                        					.addComponent(jLabel11))
                                                                                                                                                                                                        				.addComponent(TpProcedencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        			.addGap(4)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(5)
                                                                                                                                                                                                        					.addComponent(jLabel2))
                                                                                                                                                                                                        				.addComponent(TpNomeGuerra, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(4)
                                                                                                                                                                                                        					.addComponent(jLabel15))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(1)
                                                                                                                                                                                                        					.addComponent(TpMatricula, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(4)
                                                                                                                                                                                                        					.addComponent(jLabel9))
                                                                                                                                                                                                        				.addComponent(TpDataInclusao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        			.addGap(6)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(4)
                                                                                                                                                                                                        					.addComponent(jLabel17))
                                                                                                                                                                                                        				.addComponent(TpRgPm, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(jLabel16))
                                                                                                                                                                                                        				.addComponent(TpNumero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(jLabel10))
                                                                                                                                                                                                        				.addComponent(TpDataExclusao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        			.addGap(14)
                                                                                                                                                                                                        			.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        			.addGap(3)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(12)
                                                                                                                                                                                                        					.addComponent(jLabel22)
                                                                                                                                                                                                        					.addGap(14)
                                                                                                                                                                                                        					.addComponent(jLabel23))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(TpAltura, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        					.addGap(8)
                                                                                                                                                                                                        					.addComponent(TpCorPele, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(12)
                                                                                                                                                                                                        					.addComponent(jLabel19)
                                                                                                                                                                                                        					.addGap(11)
                                                                                                                                                                                                        					.addComponent(jLabel20))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(TpRgCivil, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        					.addGap(5)
                                                                                                                                                                                                        					.addComponent(TpReservista, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(jLabel18)
                                                                                                                                                                                                        					.addGap(11)
                                                                                                                                                                                                        					.addComponent(jLabel21))
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addComponent(TpCpf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        					.addGap(5)
                                                                                                                                                                                                        					.addComponent(TpPisPasep, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                                                                                                                                                                                        			.addGap(8)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(jLabel24))
                                                                                                                                                                                                        				.addComponent(TpCorOlhos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(jLabel27))
                                                                                                                                                                                                        				.addComponent(TpEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        			.addGap(8)
                                                                                                                                                                                                        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(jLabel25))
                                                                                                                                                                                                        				.addComponent(TpCorCbelos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        				.addGroup(groupLayout.createSequentialGroup()
                                                                                                                                                                                                        					.addGap(6)
                                                                                                                                                                                                        					.addComponent(jLabel26))
                                                                                                                                                                                                        				.addComponent(TpGrauInstrucao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        				.addComponent(btnEditar)
                                                                                                                                                                                                        				.addComponent(btnConfirmar))
                                                                                                                                                                                                        			.addGap(14)
                                                                                                                                                                                                        			.addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                        );
                                                                                                                                                                                                        getContentPane().setLayout(groupLayout);
        
        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JTextPane TpEstadoCivil;
    private javax.swing.JTextPane TpAltura;
    private javax.swing.JTextPane TpCorCbelos;
    private javax.swing.JTextPane TpCorOlhos;
    private javax.swing.JTextPane TpCorPele;
    private javax.swing.JTextPane TpCpf;
    private javax.swing.JTextPane TpDataExclusao;
    private javax.swing.JTextPane TpDataInclusao;
    private javax.swing.JTextPane TpDataNascimento;
    private javax.swing.JTextPane TpEmail;
    private javax.swing.JTextPane TpEspecialidade;
    private javax.swing.JTextPane TpGraduacao;
    private javax.swing.JTextPane TpGrauInstrucao;
    private javax.swing.JTextPane TpMatricula;
    private javax.swing.JTextPane TpNaturalidade;
    private javax.swing.JTextPane TpNome;
    private javax.swing.JTextPane TpNomeGuerra;
    private javax.swing.JTextPane TpNomeMae;
    private javax.swing.JTextPane TpNomePai;
    private javax.swing.JTextPane TpNumero;
    private javax.swing.JTextPane TpPisPasep;
    private javax.swing.JTextPane TpProcedencia;
    private javax.swing.JTextPane TpReservista;
    private javax.swing.JTextPane TpRgCivil;
    private javax.swing.JTextPane TpRgPm;
    private javax.swing.JTextPane TpTipoSangue;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration                   
}


