/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingUtilities;

import controler.Service;
import dao.PolicialDao;
import model.Policial;

/**
 *
 * @author Cephas
 */
public class JIFListarPoliciais extends javax.swing.JInternalFrame {

	
	private static tmListaPoliciais modelo;
	public PolicialDao pdao = new PolicialDao();
    private Service service = new Service();
    private int linhaSelecionada = -1;
    
	/**
     * Creates new form JIFListarPolicial
     */
    public JIFListarPoliciais() {
		setClosable(true);
        initComponents();
        refreshPopulate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnExcluir.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		if(linhaSelecionada != -1){
        			Policial policial = modelo.getPolicial(linhaSelecionada);
        			service.excluirPolicial(policial);
        			refreshPopulate();
        			jTable1.repaint();
        		}        	
        	}
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listar Policial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setBackground(new java.awt.Color(244, 242, 244));
        
        modelo = new tmListaPoliciais(/*pdao.listar()*/);
        jTable1.setModel(modelo);
        
        jTable1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		linhaSelecionada = jTable1.getSelectedRow();
        		
        		Point p = e.getPoint();
        		if (e.getClickCount() == 2) {
        			System.out.println(linhaSelecionada);
        			
        			Container container = SwingUtilities.getAncestorOfClass(JDesktopPane.class, (Component)e.getSource());

                    if (container != null)
                    {
                        JDesktopPane desktopPane = getDesktopPane();
                        JIFDetalhesPolicial jdp = new JIFDetalhesPolicial(modelo.getPolicial(linhaSelecionada));
                        desktopPane.add(jdp);//add f1 to desktop pane
                        jdp.setResizable(true);
            			jdp.pack();
            			jdp.setVisible(true);
                        ;
                       /* Dimension desktopSize = getDesktopPane().getSize();
                        f1.setSize(desktopSize);
                        f1.setPreferredSize(desktopSize);
                        MainClass.dontmoveframe();*/
                    } 
        			
        			
        			JIFDetalhesPolicial jdp = new JIFDetalhesPolicial(modelo.getPolicial(linhaSelecionada));
        			
        		}
        	}
        });
        
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }
        jTable1.setVisible(true);

        btnExcluir.setText("Excluir");
        
        JLabel lblCliqueDuasVezes = new JLabel("Clique duas vezes na linha para ver os detalhes do policial ou editar suas informa\u00E7\u00F5es");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblCliqueDuasVezes)
        			.addPreferredGap(ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
        			.addComponent(btnExcluir)
        			.addContainerGap())
        		.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 224, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnExcluir)
        				.addComponent(lblCliqueDuasVezes))
        			.addContainerGap(26, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        
    
    public void refreshPopulate(){
    	modelo.getLinhas().clear();
    	modelo.setLinhas(pdao.listar());
    }
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
}
